/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tenkinoko;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ACER
 */
public class demo extends javax.swing.JFrame {

    /**
     * Creates new form demo
     */
    public demo() {
        initComponents();
        initNhietKe();
        initBg();
        initTk();
        
    }

    public void initNhietKe(){
        
        ImageIcon icon = new ImageIcon("C:\\Users\\ACER\\OneDrive\\Documents\\NetBeansProjects\\TenkinoKo\\src\\tenkinoko\\nhietKe-2.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lb_nhietKe.getWidth(), lb_nhietKe.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        lb_nhietKe.setIcon(scaleIcon);
        
    }
    
    public void initBg(){
        
       // ImageIcon icon = new ImageIcon("src\\tenkinoko\\pexels-josh-sorenson-391522.jpg");
        ImageIcon icon = new ImageIcon("src\\tenkinoko\\officalBG01.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(lb_bg.getWidth(), lb_bg.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        
        lb_bg.setIcon(scaleIcon); 
        
        
        //lb_right.setBackground(new Color(255,255,255,100));
       // lb_right.setOpaque(false);
        
        
    }
    
    public void initTk(){
        
        tf_timKiem.setBackground(new Color(0,0,0,100));
        ImageIcon icon = new ImageIcon("C:\\Users\\ACER\\OneDrive\\Documents\\NetBeansProjects\\TenkinoKo\\src\\tenkinoko\\search-icon-blue-monochrome-color-vector-23770246.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(btn_find.getWidth(), btn_find.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        btn_find.setIcon(scaleIcon);
        
       //btn_find.setVisible(true);
        btn_find.setBackground(new Color(0,0,0,200));
        
        btn_find.setContentAreaFilled(false);
        btn_back.setContentAreaFilled(false);
        btn_next.setContentAreaFilled(false);
        
        
    }
           
            
            
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_nhietDo = new javax.swing.JLabel();
        lb_city = new javax.swing.JLabel();
        lb_date = new javax.swing.JLabel();
        lb_city1 = new javax.swing.JLabel();
        lb_city2 = new javax.swing.JLabel();
        lb_city3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_cloud = new javax.swing.JLabel();
        lb_humidity = new javax.swing.JLabel();
        lb_wind = new javax.swing.JLabel();
        tf_timKiem = new javax.swing.JTextField();
        lb_weather = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lb_nhietKe = new javax.swing.JLabel();
        btn_find = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lb_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nhietDo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lb_nhietDo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_nhietDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 130, 120));

        lb_city.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_city.setForeground(new java.awt.Color(255, 255, 255));
        lb_city.setText("Hà Nội");
        jPanel1.add(lb_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 60));

        lb_date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_date.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 240, 30));

        lb_city1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_city1.setForeground(new java.awt.Color(255, 255, 255));
        lb_city1.setText("Hà Nội");
        jPanel1.add(lb_city1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 86, 110, 30));

        lb_city2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_city2.setForeground(new java.awt.Color(255, 255, 255));
        lb_city2.setText("Đà Nẵng");
        jPanel1.add(lb_city2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 110, 30));

        lb_city3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_city3.setForeground(new java.awt.Color(255, 255, 255));
        lb_city3.setText("TP. Hồ Chí Minh");
        jPanel1.add(lb_city3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 120, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Weather Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 120, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cloudy");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 110, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Humidity");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 110, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Wind");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 120, 30));

        lb_cloud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_cloud.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_cloud, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 70, 30));

        lb_humidity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_humidity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_humidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 70, 30));

        lb_wind.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_wind.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_wind, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 70, 30));

        tf_timKiem.setBackground(new java.awt.Color(204, 204, 204));
        tf_timKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_timKiem.setForeground(new java.awt.Color(255, 255, 255));
        tf_timKiem.setText("Another location");
        jPanel1.add(tf_timKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 180, 40));

        lb_weather.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_weather.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lb_weather, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, 40));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 90));

        lb_nhietKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tenkinoko/nhietKe-1.png"))); // NOI18N
        lb_nhietKe.setText("jLabel19");
        jPanel1.add(lb_nhietKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 110));

        btn_find.setBackground(new java.awt.Color(204, 204, 204));
        btn_find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tenkinoko/search-icon-blue-monochrome-color-vector-23770246.jpg"))); // NOI18N
        btn_find.setText("jButton1");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });
        jPanel1.add(btn_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 40, 40));

        btn_next.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btn_next.setForeground(new java.awt.Color(255, 255, 255));
        btn_next.setText(">");
        jPanel1.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 70, 150));

        btn_back.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("<");
        jPanel1.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 70, 150));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Weather ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 360, 120));
        jPanel1.add(lb_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_findActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_find;
    private javax.swing.JButton btn_next;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bg;
    private javax.swing.JLabel lb_city;
    private javax.swing.JLabel lb_city1;
    private javax.swing.JLabel lb_city2;
    private javax.swing.JLabel lb_city3;
    private javax.swing.JLabel lb_cloud;
    private javax.swing.JLabel lb_date;
    private javax.swing.JLabel lb_humidity;
    private javax.swing.JLabel lb_nhietDo;
    private javax.swing.JLabel lb_nhietKe;
    private javax.swing.JLabel lb_weather;
    private javax.swing.JLabel lb_wind;
    private javax.swing.JTextField tf_timKiem;
    // End of variables declaration//GEN-END:variables

    public JLabel getLb_city1(){
        return lb_city1;
    }
    
    public JLabel getLb_city2(){
        return lb_city2;
    }
    
    public JLabel getLb_city3(){
        return lb_city3;
    }
    
    public JTextField getTf_timKiem(){
        return tf_timKiem;
    }
    
    public JButton getBtn_back() {
        return btn_back;
    }

    public JButton getBtn_find() {
        return btn_find;
    }

    public JButton getBtn_next() {
        return btn_next;
    }

    public JLabel getLb_city() {
        return lb_city;
    }

    public JLabel getLb_cloud() {
        return lb_cloud;
    }

    public JLabel getLb_date() {
        return lb_date;
    }

    public JLabel getLb_humidity() {
        return lb_humidity;
    }

    public JLabel getLb_nhietDo() {
        return lb_nhietDo;
    }

    public JLabel getLb_nhietKe() {
        return lb_nhietKe;
    }

    public JLabel getLb_weather() {
        return lb_weather;
    }

    public JLabel getLb_wind() {
        return lb_wind;
    }
}
